name: Alces
version: '${version}'
main: co.akoot.plugins.Alces
api-version: 1.19
authors: [ Akoot_, IndiaPaleAle ]
website: https://akoot.me/plugins/alces
description: Blocks will no longer lose their display name and lore when placed.
